pion_web:
    resource: "@PionWebBundle/Resources/config/routing.yml"
    prefix:   /web

pion_sales:
    resource: "@PionSalesBundle/Resources/config/routing.yml"
    prefix:   /sales

the_particle_bridge_website:
    resource: "@TheParticleBridgeWebsiteBundle/Resources/config/routing.yml"
    prefix:   /theparticlebridge

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin